FROM debian:trixie-slim

RUN --mount=type=tmpfs,target=/var/lib/apt/lists \
    apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends --no-install-suggests -y install \
      curl \
      iputils-ping \
      jq \
      sudo \
 && apt-get clean \
 && useradd --create-home nr5103e \
 && printf 'nr5103e ALL = NOPASSWD:SETENV: /usr/bin/nr5103e-reconnect\n' >/etc/sudoers.d/nr5103e

COPY usr/bin /usr/bin
COPY --chmod=0600 tmp /tmp

USER nr5103e
WORKDIR /home/nr5103e

RUN mkfifo --mode=0600 /home/nr5103e/nr5103e.fifo

ENV NR5103E_IP='192.168.1.1'
ENV NR5103E_WAIT_DOWN=15

ENTRYPOINT [ "/usr/bin/nr5103e-entrypoint" ]
